services:
  backend-module:
    build: 
      context: ./backend-module
      dockerfile: Dockerfile
    image: leoalmeida/backend-module:latest
    container_name: backend-module
    ports:
      - ${{ secrets.SPRING_LOCAL_PORT }}:${{ secrets.SPRING_DOCKER_PORT }}
    environment: 
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "${{ secrets.DB_URL }}",
          "spring.datasource.username" : "${{ secrets.DB_USERNAME }}",
          "spring.datasource.password" : "${{ secrets.DB_PASSWORD }}",
          "spring.datasource.driver-class-name" : "${{ secrets.DB_DRIVER }}"
        }' 
    networks:
      - app-network
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: leoalmeida/frontend:latest
    container_name: frontend
    ports:
      - ${{ secrets.FRONTEND_LOCAL_PORT }}:${{ secrets.FRONTEND_DOCKER_PORT }}
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend-module
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

