CREATE TABLE BENEFICIO (
  ID BIGINT NOT NULL auto_increment,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(255),
  VALOR DECIMAL(15,2) NOT NULL,
  ATIVO BOOLEAN DEFAULT TRUE,
  VERSION BIGINT DEFAULT 0,
  PRIMARY KEY (id)
);
